package javaapplication1;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.DefaultListModel;
//import javax.swing.DefaultListSelectionModel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.ListModel;
import javax.swing.UIManager;

/**
 *
 * @author K00213054
 */
public class A2ZTransit extends javax.swing.JFrame {

    private ArrayList<Package> packageList = new ArrayList();
    public int id = 0;
    public int Index = - 1;
    //public int nextIndex = -1;
    public String timeArrived = setArrivalTime();

    ResourceBundle rb = ResourceBundle.getBundle("RBundle.MyResourceBundle");
    Locale[] locales = {new Locale("en", "IE"), new Locale("de", "DE"), new Locale("fr", "FR")};

    DefaultListModel<String> model = new DefaultListModel<String>();

    //https://www.youtube.com/watch?v=w7xiY0fc6cs
    /**
     * Creates new form A2ZTransit
     */
    public A2ZTransit() {
        initComponents();
        updateAll(locales[0]);

        nameTxtField.setEnabled(false);
        addressTxtField.setEnabled(false);
        cityTxtField.setEnabled(false);
        contactNoTxtField.setEnabled(false);
        descriptionTxtField.setEnabled(false);
        priceTxtField.setEnabled(false);

        scanBtn.setEnabled(true);
        removeBtn.setEnabled(false);
        backBtn.setEnabled(false);
        editBtn.setEnabled(false);
        updateBtn.setEnabled(false);
        nextBtn.setEnabled(false);
        displayBtn.setEnabled(false);
        addBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    /*http://www.java2s.com/Code/Java/Swing-JFC/CreateJListfromarrayofstringvalue.htm
    /http://www.java2s.com/Code/Java/Swing-JFC/CreateJListfromarrayofstringvalue.htm
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        arrivalLabel = new javax.swing.JLabel();
        arrivalTimeTxtField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        packageLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        packageIDTxtField = new javax.swing.JTextField();
        nameTxtField = new javax.swing.JTextField();
        addressTxtField = new javax.swing.JTextField();
        cityTxtField = new javax.swing.JTextField();
        countyLabel = new javax.swing.JLabel();
        contactNoLabel = new javax.swing.JLabel();
        countyComboBox = new javax.swing.JComboBox<>();
        contactNoTxtField = new javax.swing.JTextField();
        descriptionTxtField = new javax.swing.JTextField();
        priceTxtField = new javax.swing.JTextField();
        prepaidLabel = new javax.swing.JLabel();
        yesRadioBtn = new javax.swing.JRadioButton();
        noRadioBtn = new javax.swing.JRadioButton();
        scanBtn = new javax.swing.JToggleButton();
        addBtn = new javax.swing.JToggleButton();
        removeBtn = new javax.swing.JToggleButton();
        editBtn = new javax.swing.JToggleButton();
        updateBtn = new javax.swing.JToggleButton();
        backBtn = new javax.swing.JToggleButton();
        nextBtn = new javax.swing.JToggleButton();
        displayBtn = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        packageIDList = new javax.swing.JList<>();
        irishBtn = new javax.swing.JButton();
        germanBtn = new javax.swing.JButton();
        frenchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        arrivalLabel.setText("Arrived at:");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setToolTipText("Package Information");
        jPanel2.setName("Package Information"); // NOI18N

        packageLabel.setText("Package ID:");

        nameLabel.setText("Name:");

        addressLabel.setText("Address:");

        cityLabel.setText("City:");

        descriptionLabel.setText("Description:");

        priceLabel.setText("Price:");

        countyLabel.setText("County:");

        contactNoLabel.setText("Contact Num:");

        countyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clare", "Limerick", "Tipperary", "Laois", "Kildare", "Dublin" }));
        countyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countyComboBoxActionPerformed(evt);
            }
        });

        prepaidLabel.setText("Prepaid:");

        buttonGroup1.add(yesRadioBtn);
        yesRadioBtn.setText("Yes");

        buttonGroup1.add(noRadioBtn);
        noRadioBtn.setText("No");

        scanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ScanNow.gif"))); // NOI18N
        scanBtn.setText("Scan Now");
        scanBtn.setName(""); // NOI18N
        scanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scanBtnActionPerformed(evt);
            }
        });

        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/add.gif"))); // NOI18N
        addBtn.setText("Add");
        addBtn.setName(""); // NOI18N
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        removeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/remove.gif"))); // NOI18N
        removeBtn.setText("Remove");
        removeBtn.setName(""); // NOI18N
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/edit.gif"))); // NOI18N
        editBtn.setText("Edit");
        editBtn.setName(""); // NOI18N
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/uipdate.gif"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.setName(""); // NOI18N
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/back.gif"))); // NOI18N
        backBtn.setText("Back");
        backBtn.setName(""); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        nextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/next.gif"))); // NOI18N
        nextBtn.setText("Next");
        nextBtn.setName(""); // NOI18N
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        displayBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/display.gif"))); // NOI18N
        displayBtn.setText("Display All");
        displayBtn.setName(""); // NOI18N
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(packageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(priceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(prepaidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(yesRadioBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(noRadioBtn))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(countyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(countyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(contactNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(contactNoTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                            .addComponent(packageIDTxtField)
                            .addComponent(nameTxtField)
                            .addComponent(addressTxtField)
                            .addComponent(descriptionTxtField))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(scanBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBtn)
                        .addGap(10, 10, 10)
                        .addComponent(removeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayBtn)
                        .addGap(0, 16, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(packageIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(addressTxtField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(countyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cityTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(countyComboBox)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(contactNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(contactNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cityLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prepaidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(yesRadioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addComponent(noRadioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                    .addComponent(priceTxtField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scanBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nextBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clare", "Limerick", "Tipperary", "Laois", "Kildare", "Dublin" }));
        jPanel3.add(jComboBox2);
        jComboBox2.setBounds(10, 10, 260, 25);

        jScrollPane1.setViewportView(packageIDList);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(12, 45, 255, 210);

        irishBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/irish-flag.jpg"))); // NOI18N
        irishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irishBtnActionPerformed(evt);
            }
        });

        germanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/germany-flag.jpg"))); // NOI18N
        germanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                germanBtnActionPerformed(evt);
            }
        });

        frenchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/french-flag.jpg"))); // NOI18N
        frenchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frenchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(arrivalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(arrivalTimeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(irishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(germanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frenchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frenchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(germanBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(irishBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(arrivalTimeTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(arrivalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 5, 1240, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void irishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irishBtnActionPerformed
        updateAll(locales[0]);

    }//GEN-LAST:event_irishBtnActionPerformed

    private void germanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_germanBtnActionPerformed
        updateAll(locales[1]);
    }//GEN-LAST:event_germanBtnActionPerformed

    private void frenchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frenchBtnActionPerformed
        updateAll(locales[2]);
    }//GEN-LAST:event_frenchBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed

        //int index = parcelIDList.getSelectedIndex();
        model.addElement("" + packageIDTxtField.getText());
        packageIDList.setModel(model);

        String output = "";

        for (Package pack : packageList) { //TxtArea gets details from pack of the array list which include added orders

            output += "Package ID: " + pack.getPackageID()
            + "\nDate\tTime Arrived " + pack.getArrivalTime()
            + "\nName " + pack.getName()
            + "\nAddress " + pack.getAddress()
            + "\nCity " + pack.getCity()
            + "\nCounty " + pack.getCounty()
            + "\nContact Number " + pack.getContactNumber()
            + "\nDescription " + pack.getDescription()
            + "\nPrice " + pack.getPrice() + "\nPrepaid " + pack.isPrePaid() + "\n\n";

        }
        //parcelIDList.add(output, this);
        JOptionPane.showMessageDialog(null, output, " Packages ", JOptionPane.INFORMATION_MESSAGE);
        //JOptionPane.showMessageDialog(null, "List of ordered products: " + packageList.size());
    }//GEN-LAST:event_displayBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        if (Index == packageList.size() - 1) {
            nextBtn.setEnabled(false);
        } else {
            int next = Index + 1;

            //nextIndex++;
            packageIDTxtField.setText("" + packageList.get(next).getPackageID());
            nameTxtField.setText("" + packageList.get(next).getName());
            addressTxtField.setText("" + packageList.get(next).getAddress());
            cityTxtField.setText("" + packageList.get(next).getCity());
            contactNoTxtField.setText("" + packageList.get(next).getContactNumber());
            descriptionTxtField.setText("" + packageList.get(next).getDescription());
            priceTxtField.setText("" + packageList.get(next).getPrice());

            if (packageList.get(next).isPrePaid()) {
                yesRadioBtn.setEnabled(true);
            } else {
                noRadioBtn.setEnabled(true);
            }
            Index++;
        }
        if(Index == packageList.size() -1) {
            nextBtn.setEnabled(false);
        }

        backBtn.setEnabled(true);
        editBtn.setEnabled(true);
        removeBtn.setEnabled(true);
    }//GEN-LAST:event_nextBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        if(Index == 0) {
            backBtn.setEnabled(false);
        } else {
            int back = Index - 1;

            packageIDTxtField.setText("" + packageList.get(back).getPackageID());
            nameTxtField.setText("" + packageList.get(back).getName());
            addressTxtField.setText("" + packageList.get(back).getAddress());
            cityTxtField.setText("" + packageList.get(back).getCity());
            contactNoTxtField.setText("" + packageList.get(back).getContactNumber());
            descriptionTxtField.setText("" + packageList.get(back).getDescription());
            priceTxtField.setText("" + packageList.get(back).getPrice());

            if (packageList.get(back).isPrePaid()) {
                yesRadioBtn.setEnabled(true);
            } else {
                noRadioBtn.setEnabled(true);

            }

            Index--;
        }
        if(Index == 0) {
            backBtn.setEnabled(false);
        }
        nextBtn.setEnabled(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try {

            double price = Double.parseDouble(priceTxtField.getText());
            //int index = Integer.parseInt(packageIDList.getSelectedValue()); // get ID from the JList. Parse it...

            for (int i = 0; i < packageList.size(); i++) { //loop through the array list of packages
                if (packageList.get(i).getPackageID() == Integer.parseInt(packageIDTxtField.getText())) {

                    packageList.get(i).setPackage(nameTxtField.getText(), addressTxtField.getText(),
                        cityTxtField.getText(), countyComboBox.getSelectedItem().toString(),
                        contactNoTxtField.getText(), descriptionTxtField.getText(),
                        price, yesRadioBtn.isSelected()
                    );

                }
            }

            //Use geter/setter methods to change the details for that package.
            //             String name = nameTxtField.getText();
            //             packageList.get(i).setName(name);
            //
            //             String address = addressTxtField.getText();
            //             packageList.get(i).setAddress(address);
            //
            //             String city = cityTxtField.getText();
            //             packageList.get(i).setCity(city);
            //
            //             String county = (String) countyComboBox.getSelectedItem(); //...getSelectedItem().toString(); is similar to this statement
            //             packageList.get(i).setCounty(county);
            addBtn.setEnabled(false);
            scanBtn.setEnabled(true);
            editBtn.setEnabled(true);
            updateBtn.setEnabled(false);
            backBtn.setEnabled(true);
            nextBtn.setEnabled(true);
            displayBtn.setEnabled(true);
            removeBtn.setEnabled(true);

            nameTxtField.setEditable(true);
            addressTxtField.setEditable(true);
            cityTxtField.setEditable(true);
            contactNoTxtField.setEditable(true);
            descriptionTxtField.setEditable(true);
            priceTxtField.setEditable(true);

            //             try{
                //
                //                 int contactNumber = Integer.parseInt(contactNoTxtField.getText());
                //                 packageList.get(i).setContactNumber(contactNumber);
                //             } catch (Exception e) {
                //                 JOptionPane.showMessageDialog(null, " Contact Number must be an integer value ");
                //             }
            //
            //             String Description = descriptionTxtField.getText();
            //             packageList.get(i).setDescription(Description);
            //
            //             try {
                //
                //                 //double price = Double.parseDouble(priceTxtField.getText());
                //                 packageList.get(i).setPrice(price);
                //             } catch (Exception e){
                //                 JOptionPane.showMessageDialog(null, " The price must have a numeric value");
                //                     }
            //             boolean prepaid;
            //
            //             if(yesRadioBtn.isSelected()){
                //             prepaid = true;
                //
                //             packageList.get(i).setPrePaid(prepaid);
                //
                //         } else {
                //                 noRadioBtn.isSelected();
                //                 prepaid = false;
                //             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, " Price must have a numeric value ");
        }

    }//GEN-LAST:event_updateBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        try {
            double price = Double.parseDouble(priceTxtField.getText());
        
        nameTxtField.setEnabled(true);
        addressTxtField.setEnabled(true);
        cityTxtField.setEnabled(true);
        contactNoTxtField.setEnabled(true);
        descriptionTxtField.setEnabled(true);
        priceTxtField.setEnabled(true);

        nameTxtField.setEditable(true);
        addressTxtField.setEditable(true);
        cityTxtField.setEditable(true);
        contactNoTxtField.setEditable(true);
        descriptionTxtField.setEditable(true);
        priceTxtField.setEditable(true);

        scanBtn.setEnabled(false);
        addBtn.setEnabled(false);
        removeBtn.setEnabled(false);    
        editBtn.setEnabled(true);
        updateBtn.setEnabled(true);
        backBtn.setEnabled(false);
        nextBtn.setEnabled(false);
        displayBtn.setEnabled(false);
    } catch (Exception e){
        JOptionPane.showMessageDialog(null, " Please enter a valid number for price");
            UIManager.put("OptionPane.YEsButtonText", rb.getString("Valores tem de ser numericos"));
    }
    }//GEN-LAST:event_editBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed

        int response = JOptionPane.showConfirmDialog(null, "Package will be permanently deleted.", "Alert Window", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);

        for(Package p : packageList){
            if(p.getPackageID() == Integer.parseInt(packageIDTxtField.getText()));
            packageList.remove(p);
            break;
        }

    }//GEN-LAST:event_removeBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try { 
            
            double price = Double.parseDouble(priceTxtField.getText()); //parsing double to string to getTexr
            
        Package p = new Package();//create new package object

        nameTxtField.setEnabled(false);
        addressTxtField.setEnabled(false);
        cityTxtField.setEnabled(false);
        contactNoTxtField.setEnabled(false);
        descriptionTxtField.setEnabled(false);
        priceTxtField.setEnabled(false);

        scanBtn.setEnabled(true);
        addBtn.setEnabled(false);
        editBtn.setEnabled(false);
        updateBtn.setEnabled(false);
        backBtn.setEnabled(false);
        nextBtn.setEnabled(false);
        removeBtn.setEnabled(true);

        
        if (packageList.size() >= 1) { //enable btn (true)in case the package list size is >= 1; False otherwise
            displayBtn.setEnabled(true);
        } else {
            displayBtn.setEnabled(false);
        }

        p.setPackageID(id);
        p.setArrivalTime(timeArrived);

        String name = nameTxtField.getText();
        p.setName(name);

        String address = addressTxtField.getText();
        p.setAddress(address);

        String city = cityTxtField.getText();
        p.setCity(city);

        String contact = contactNoTxtField.getText();
        p.setContactNumber(contact);
        
        int contactNumber = (Integer.parseInt(contactNoTxtField.getText()));
        p.setContactNumber(contact);

        String description = descriptionTxtField.getText();
        p.setDescription(description);

        String county = countyComboBox.getSelectedItem().toString();
        p.setCounty(county);

        yesRadioBtn.isSelected();

        //       boolean prepaid;
        //       if(yesLabel.isSelected()){
            //        noLabel.setEnabled(false);
            //        prepaid = true;
            //
            //        p.setPrePaid(prepaid);
            //    } else {
            //           yesLabel.setEnabled(false);
            //            prepaid = false;
            //       }
        packageList.add(p);
        id++;
        //id = id + 1;
        if (packageList.size() >= 2) {
            backBtn.setEnabled(true);
            nextBtn.setEnabled(true);
            updateBtn.setEnabled(true);
            editBtn.setEnabled(true);
        } else {
            backBtn.setEnabled(false);
            nextBtn.setEnabled(false);
        }

        Index++;

        if(Index == packageList.size() - 1) {
            nextBtn.setEnabled(false);
        }
        
}catch (Exception e) {
    JOptionPane.showMessageDialog(null, " Please input valid number for price ");
}
    

    }//GEN-LAST:event_addBtnActionPerformed

    private void scanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scanBtnActionPerformed

        packageIDTxtField.setEnabled(false);
        packageIDTxtField.setText("" + id);
        arrivalTimeTxtField.setEnabled(false);
        arrivalTimeTxtField.setText("" + timeArrived); // set time to the arrival txtField

        //clear txtFields once scan btn is selected.
        nameTxtField.setText("");
        addressTxtField.setText("");
        cityTxtField.setText("");
        contactNoTxtField.setText("");
        descriptionTxtField.setText("");
        priceTxtField.setText("");

        nameTxtField.setEnabled(true);
        addressTxtField.setEnabled(true);
        cityTxtField.setEnabled(true);
        contactNoTxtField.setEnabled(true);
        descriptionTxtField.setEnabled(true);
        priceTxtField.setEnabled(true);

        scanBtn.setEnabled(true);
        removeBtn.setEnabled(false);
        backBtn.setEnabled(false);
        editBtn.setEnabled(false);
        updateBtn.setEnabled(false);
        nextBtn.setEnabled(false);
        displayBtn.setEnabled(false);
        addBtn.setEnabled(true);
    }//GEN-LAST:event_scanBtnActionPerformed

    private void countyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countyComboBoxActionPerformed
        //not used - none action is needed
    }//GEN-LAST:event_countyComboBoxActionPerformed

    private void updateAll(Locale locales) {
        rb = ResourceBundle.getBundle("RBundle.MyResourceBundle", locales);

        arrivalLabel.setText(rb.getString("arrivalLabel"));
        packageLabel.setText(rb.getString("packageLabel"));
        nameLabel.setText(rb.getString("nameLabel"));
        addressLabel.setText(rb.getString("addressLabel"));
        cityLabel.setText(rb.getString("cityLabel"));
        countyLabel.setText(rb.getString("countyLabel"));
        contactNoLabel.setText(rb.getString("contactNoLabel"));
        descriptionLabel.setText(rb.getString("descriptionLabel"));
        priceLabel.setText(rb.getString("priceLabel"));
        prepaidLabel.setText(rb.getString("prepaidLabel"));
        yesRadioBtn.setText(rb.getString("yesLabel"));
        noRadioBtn.setText(rb.getString("noLabel"));

        scanBtn.setText(rb.getString("scanLabel"));
        addBtn.setText(rb.getString("addLabel"));
        removeBtn.setText(rb.getString("removeLabel"));
        editBtn.setText(rb.getString("editLabel"));
        updateBtn.setText(rb.getString("updateLabel"));
        backBtn.setText(rb.getString("backLabel"));
        nextBtn.setText(rb.getString("nextLabel"));
        displayBtn.setText(rb.getString("displayLabel"));

//       GregorianCalendar cal = new GregorianCalendar();
//        DateFormat formatter = DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.MEDIUM, locales);
//        String date = formatter.format(cal.getTime());
//        arrivalLabel.setText(date);  
    }

    private String setArrivalTime() {
        Date d = new Date();
        SimpleDateFormat at = new SimpleDateFormat(" MM-dd z 'at' hh:mm:ss");
        return at.format(d);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A2ZTransit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A2ZTransit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A2ZTransit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A2ZTransit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A2ZTransit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addBtn;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTxtField;
    private javax.swing.JLabel arrivalLabel;
    private javax.swing.JTextField arrivalTimeTxtField;
    private javax.swing.JToggleButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTxtField;
    private javax.swing.JLabel contactNoLabel;
    private javax.swing.JTextField contactNoTxtField;
    private javax.swing.JComboBox<String> countyComboBox;
    private javax.swing.JLabel countyLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionTxtField;
    private javax.swing.JToggleButton displayBtn;
    private javax.swing.JToggleButton editBtn;
    private javax.swing.JButton frenchBtn;
    private javax.swing.JButton germanBtn;
    private javax.swing.JButton irishBtn;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JToggleButton nextBtn;
    private javax.swing.JRadioButton noRadioBtn;
    private javax.swing.JList<String> packageIDList;
    private javax.swing.JTextField packageIDTxtField;
    private javax.swing.JLabel packageLabel;
    private javax.swing.JLabel prepaidLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTxtField;
    private javax.swing.JToggleButton removeBtn;
    private javax.swing.JToggleButton scanBtn;
    private javax.swing.JToggleButton updateBtn;
    private javax.swing.JRadioButton yesRadioBtn;
    // End of variables declaration//GEN-END:variables
}
